version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_api
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      - DB_HOST=db
      - DB_NAME=sensor_system
      - DB_USER=sensor_user
      - DB_PASS=sensor_password
    depends_on:
      - db
    networks:
      - sensor-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: sensor_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=sensor_system
      - MYSQL_USER=sensor_user
      - MYSQL_PASSWORD=sensor_password
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - sensor-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sensor_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - sensor-network
    restart: unless-stopped

networks:
  sensor-network:
    driver: bridge

volumes:
  mysql_data:
